// vueJs/vuejsExpense/src/components/AddTask.vue
<template>
  <form @submit="onSubmint" class="add-form">
    <div class="form-control">
      <label>Tarefa</label>
      <input
        type="text"
        v-model="text"
        name="text"
        placeholder="Adicione tarefa"
      />
    </div>
    <div class="form-control">
      <label>Data e Horário</label>
      <input
        type="text"
        v-model="day"
        name="day"
        placeholder="Adicione data e horário"
      />
    </div>
    <div class="form-control form-control-check">
      <label>Lembrar</label>
      <input type="checkbox" v-model="reminder" name="reminder" />
    </div>

    <input type="submit" value="Salvar Tarefa" class="btn btn-block" />
  </form>
</template>

<script>
export default {
  name: "AddTask",
  data() {
    return {
      text: "",
      day: "",
      reminder: false,
    };
  },
  methods: {
    onSubmint(e) {
      e.preventDefault();
      if (!this.text) {
        alert("Preencha o campo Tarefa");
        return;
      }
      if (!this.day) {
        alert("Preencha o campo Data e Hora");
        return;
      }

      const newTask = {
        // id: Math.floor(Math.random() * 10000),
        text: this.text,
        day: this.day,
        reminder: this.reminder,
      };

      this.$emit('add-task', newTask);

      this.text = "";
      this.day = "";
      this.reminder = "";
    },
  },
};
</script>

<style scoped>
.add-form {
  margin-bottom: 40px;
}
.form-control {
  margin: 20px 0;
}
.form-control label {
  display: block;
}
.form-control input {
  width: 100%;
  height: 40px;
  margin: 5px;
  padding: 3px 7px;
  font-size: 17px;
}
.form-control-check {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.form-control-check label {
  flex: 1;
}
.form-control-check input {
  flex: 2;
  height: 20px;
}
</style>

// angular/angularExpense/src/app/components/add-task/add-task.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { UiService } from '../../services/ui.service';
import { Subscription } from 'rxjs';
import { Task } from '../../Task';

@Component({
  selector: 'app-add-task',
  templateUrl: './add-task.component.html',
  styleUrls: ['./add-task.component.css'],
})
export class AddTaskComponent {
  @Output() onAddTask: EventEmitter<Task> = new EventEmitter();
  text!: string;
  day!: string;
  reminder: boolean = false;
  showAddTask!: boolean;
  subscription!: Subscription;

  constructor(private uiService: UiService) {
    this.subscription = this.uiService
      .onToggle()
      .subscribe((value) => (this.showAddTask = value));
  }

  onSubmit() {
    if (!this.text) {
      alert('Preencha o campo tarefa');
      return;
    }
    if (!this.day) {
      alert('Preencha o campo Data e Hora');
      return;
    }

    const newTask = {
      text: this.text,
      day: this.day,
      reminder: this.reminder,
    };

    this.onAddTask.emit(newTask);

    this.text = '';
    this.day = '';
    this.reminder = false;
  }
}

<form *ngIf="showAddTask" class="add-form" (ngSubmit)="onSubmit()">
  <div class="form-control">
    <label for="text">Tarefa</label>
    <input
      type="text"
      name="text"
      id="text"
      [(ngModel)]="text"
      placeholder="Adicionar tarefa"
    />
  </div>
  <div class="form-control">
    <label for="day">Dia e Hora</label>
    <input
      type="text"
      name="day"
      id="day"
      [(ngModel)]="day"
      placeholder="Adicionar tarefa"
    />
  </div>
  <div class="form-control form-control-check">
    <label for="reminder">Lembrete</label>
    <input
      type="checkbox"
      name="reminder"
      id="reminder"
      [(ngModel)]="reminder"
    />
  </div>
  <input type="submit" value="Salvar tarefa" class="btn btn-block" />
</form>
